name: Lint

on:
  push:
    branches: [master]
    paths:
      - grammar.mjs
  pull_request:
    paths:
      - grammar.mjs

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          cache: npm
          node-version: ${{vars.NODE_VERSION}}
      - name: Install modules
        run: npm ci --legacy-peer-deps
      - name: Run ESLint
        run: npm run lint
